---
- hosts: all 
  become: yes
  tasks:
  - name: Set timezone to Africa/Lagos
    timezone:
      name: Africa/Lagos
  - name: Install latest version of Apache
    apt: name=apache2 update_cache=yes state=latest
  - name: print hostname on server
    shell: echo "<h1>This is my server name $(hostname -f)</h1>" > /var/www/html/index.html
  - name: restart apache2
    service:
      name: apache2
      state: restarted
